name: rsa_pkcs
version: 0.1.1
author: Alexandre Maurel <alexandre.maurel@gmail.com>
description: RSA,PKCS#1,PKCS#8
homepage: https://github.com/amaurel/rsa_pkcs
dependencies:
  asn1lib: any
  cipher:
    git: git://github.com/SecareLupus/cipher.git
dev_dependencies:
  crypto: any 
  unittest: any
